/// Flutter icons MyPack
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPack
///      fonts:
///       - asset: fonts/MyPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData description = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zagolovok = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pointer_ddprgqpk49dc = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase_klvunb0cozwu = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job_description_kwo7og605c2l = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_k1ojits0gzbu = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
