/// Flutter icons IconPack
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';
  static const String? _kFontPkg = null;

  static const IconData market = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData style = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb = IconData(0xf0eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
